### ISSUE TITLE
Design Of a Helical Spring

### ISSUE THREAD

**Issue by mugdhapendse** [DevSnowflake/code-examples#150]
Anyone (literally) will be able to compute the dimensions of a helical spring by giving inputs like the maximum weight attached, length of the scale, ultimate tensile strength, spring Index,  and modulus of rigidity.

**Comment by pandyaved98** [comment]
What we are supposed to do in this? Implementation of equations? @mugdhapendse

**Comment by mugdhapendse** [comment]
No, equations have already been added to the code. You only have to give certain inputs like those mentioned in the previous comment. Then you will have the design parameters required for the helical spring.

**Comment by mugdhapendse** [comment]
It'd be great if this could be assigned to me under hacktoberfest tag!

**Comment by rhydderchc** [comment]
@mugdhapendse open a pr and we'll link it with this **issue**.

**Comment by rhygg** [comment]
# This issue is be closed due to no apparent activity.
