### ISSUE TITLE
Seems like the project is excluded 

### ISSUE THREAD

**Issue by madda01** [DevSnowflake/code-examples#255]

**Comment by gympohnpimol** [comment]
I found the same problem. What is happening?

**Comment by rhydderchc** [comment]
?
I don't understand what you mean by "excluded"?

**Comment by madda01** [comment]
> ? I don't understand what you mean by "excluded"?
 hey :) 
oh, I meant was previously the project was participating in the hacktoberfest now we get it as 'excluded project'.

**Comment by madda01** [comment]
> we have decided to turn this into a code example website

glad to be a part of it :)
