### ISSUE TITLE
Redirect if directory doesn't work on home page

### ISSUE THREAD

**Issue by rhygg** [DevSnowflake/code-examples#329]
![Peek 2021-11-21 10-21](https://user-images.githubusercontent.com/72539206/142770210-45ec0366-6f8d-4f23-a642-809c91b8be07.gif)

**Comment by DevAndromeda** [comment]
- the website crash should be fixed by 58d08e88223e623530cf19f5713bee369e032c5e
- the redirect issue should be fixed by 5e2d643539dec723a9f0d4e4beadb84376d4b81f
